Repository PetGoorm/backend, pull requests merged in 2023-09, with the labels that each got.

#14 (feat & refactor: 게시판에 간단한 페이징 기능 및 카테고리 별 게시물 목록 조회 기능 추가 / 500 에러 메세지 수정)
  src/main/java/com/petgoorm/backend/controller/BoardController.java
  src/main/java/com/petgoorm/backend/repository/BoardRepository.java
  src/main/java/com/petgoorm/backend/service/BoardService.java
  src/main/java/com/petgoorm/backend/service/BoardServiceImpl.java
Labels: ✨ Feature, 🛠️ Refactor

#16 (feat: 댓글 조회 및 등록 기능 추가)
  src/main/java/com/petgoorm/backend/controller/ReplyController.java
  src/main/java/com/petgoorm/backend/dto/board/BoardRequestDTO.java
  src/main/java/com/petgoorm/backend/dto/board/BoardResponseDTO.java
  src/main/java/com/petgoorm/backend/entity/Reply.java
  src/main/java/com/petgoorm/backend/repository/ReplyRepository.java
  src/main/java/com/petgoorm/backend/service/ReplyService.java
  src/main/java/com/petgoorm/backend/service/ReplyServiceImpl.java
  src/test/java/com/petgoorm/backend/ReplyTests.java
Labels: enhancement, 🔰BE, ✨ Feature

#15 (feat: 검색 기능 추가)
  src/main/java/com/petgoorm/backend/controller/BoardController.java
  src/main/java/com/petgoorm/backend/repository/BoardRepository.java
  src/main/java/com/petgoorm/backend/service/BoardService.java
  src/main/java/com/petgoorm/backend/service/BoardServiceImpl.java
Labels: enhancement, 🔰BE, ✨ Feature

#17 ( refactor & feat )조회수 기능 구현을 위한 DTO 구조 수정 / 레디스로 게시물 조회수 캐싱 / 스케줄러로 캐시 관리
  .gitignore
  src/main/java/com/petgoorm/backend/BackendApplication.java
  src/main/java/com/petgoorm/backend/config/RedisViewCountScheduler.java
  src/main/java/com/petgoorm/backend/controller/BoardController.java
  src/main/java/com/petgoorm/backend/dto/board/BoardRequestDTO.java
  src/main/java/com/petgoorm/backend/dto/board/BoardResponseDTO.java
  src/main/java/com/petgoorm/backend/entity/Board.java
  src/main/java/com/petgoorm/backend/repository/BoardRepository.java
  src/main/java/com/petgoorm/backend/service/BoardService.java
  src/main/java/com/petgoorm/backend/service/BoardServiceImpl.java
  src/main/java/com/petgoorm/backend/service/RedisBoardService.java
  src/main/java/com/petgoorm/backend/service/RedisBoardServiceImpl.java
Labels: 🔰BE
