Repository PetGoorm/backend, pull requests merged in 2023-08, with the labels that each got.

#10 (feat: TodoList 날짜 별로 값 받아오기)
  src/main/java/com/petgoorm/backend/controller/ToDoController.java
  src/main/java/com/petgoorm/backend/dto/todo/ToDoDTO.java
  src/main/java/com/petgoorm/backend/entity/ToDo.java
  src/main/java/com/petgoorm/backend/repository/ToDoRepository.java
  src/main/java/com/petgoorm/backend/service/ToDoService.java
  src/main/java/com/petgoorm/backend/service/ToDoServiceImpl.java
Labels: 🔰BE, ✨ Feature

#11 (Feat & Refactor) 게시판 목록 조회 API 추가 & 글 수정 API 리팩토링
  build.gradle
  src/main/java/com/petgoorm/backend/controller/BoardController.java
  src/main/java/com/petgoorm/backend/dto/board/BoardResponseDTO.java
  src/main/java/com/petgoorm/backend/repository/BoardRepository.java
  src/main/java/com/petgoorm/backend/service/BoardService.java
  src/main/java/com/petgoorm/backend/service/BoardServiceImpl.java
Labels: 🔰BE, ✨ Feature, 🛠️ Refactor

#12 (feat: 사용자의 주소에 맞는 글 목록 불러오는 기능 추가)
  src/main/java/com/petgoorm/backend/controller/BoardController.java
  src/main/java/com/petgoorm/backend/repository/BoardRepository.java
  src/main/java/com/petgoorm/backend/service/BoardService.java
  src/main/java/com/petgoorm/backend/service/BoardServiceImpl.java
Labels: enhancement, 🔰BE, ✨ Feature
