Repository PetGoorm/backend, pull requests merged in 2023-10, with the labels that each got.

#18 (feat: 댓글 수정, 삭제 기능 추가 및 법정동 코드 칼럼 추가)
  src/main/java/com/petgoorm/backend/config/WebSecurityConfig.java
  src/main/java/com/petgoorm/backend/controller/ReplyController.java
  src/main/java/com/petgoorm/backend/dto/board/BoardResponseDTO.java
  src/main/java/com/petgoorm/backend/dto/member/MemberRequestDTO.java
  src/main/java/com/petgoorm/backend/entity/Member.java
  src/main/java/com/petgoorm/backend/entity/Reply.java
  src/main/java/com/petgoorm/backend/repository/ReplyRepository.java
  src/main/java/com/petgoorm/backend/service/MemberService.java
  src/main/java/com/petgoorm/backend/service/ReplyService.java
  src/main/java/com/petgoorm/backend/service/ReplyServiceImpl.java
  src/test/java/com/petgoorm/backend/ReplyTests.java
Labels: enhancement, 🔰BE, ✨ Feature

#19 (feat: 펫다이어리 CRUD 구현)
  src/main/java/com/petgoorm/backend/controller/PetdiaryController.java
  src/main/java/com/petgoorm/backend/dto/petdiary/PetdiaryRequestDTO.java
  src/main/java/com/petgoorm/backend/dto/petdiary/PetdiaryResponseDTO.java
  src/main/java/com/petgoorm/backend/entity/PetDiary.java
  src/main/java/com/petgoorm/backend/repository/PetDiaryRepository.java
  src/main/java/com/petgoorm/backend/service/PetdiaryService.java
  src/main/java/com/petgoorm/backend/service/PetdiaryServiceImpl.java
Labels: 🔰BE, ✨ Feature

#21 (feat: 에러 핸들링 기능 추가)
  src/main/java/com/petgoorm/backend/config/WebSecurityConfig.java
  src/main/java/com/petgoorm/backend/dto/ResponseDTO.java
  src/main/java/com/petgoorm/backend/handler/CustomAccessDeniedHandler.java
  src/main/java/com/petgoorm/backend/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/petgoorm/backend/handler/CustomException.java
  src/main/java/com/petgoorm/backend/handler/ErrorCode.java
  src/main/java/com/petgoorm/backend/handler/ExceptionHandler.java
  src/main/java/com/petgoorm/backend/jwt/JwtAuthenticationFilter.java
  src/main/java/com/petgoorm/backend/jwt/JwtTokenProvider.java
  src/main/java/com/petgoorm/backend/service/MemberServiceImpl.java
  src/main/java/com/petgoorm/backend/service/ReplyServiceImpl.java
Labels: 🐞 BugFix, enhancement, ✨ Feature

#22 (fix: 반려일지 day 중복 에러 수정)
  src/main/java/com/petgoorm/backend/repository/PetDiaryRepository.java
  src/main/java/com/petgoorm/backend/service/PetdiaryServiceImpl.java
Labels: 🐞 BugFix, 🔰BE
